# Generated by Django 4.1.1 on 2022-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic_file',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pictures', verbose_name='Choose a picture'),
        ),
    ]
